name: notebooks_env


channels:
  - astropy
  - http://ssb.stsci.edu/astroconda
  - defaults
  - glueviz/label/dev
  - glueviz

dependencies:
  - pip
  - numpy
  - astropy
  - scipy
  - astroquery
  - matplotlib
  - jupyter
  - pandas
  - drizzlepac
  - crds
  - ccdproc
  - acstools
  - photutils>=0.6
  - regions
  - pyregion
  - webbpsf>=0.8
  - scikit-learn
  - lmfit>=0.9
  - specutils
  - dill
  - dust_extinction
  - bottleneck
  - drizzle
  - h5py
  - nodejs
  
  - pip:
    - k2flix
    - junit_xml
    - git+https://github.com/eteq/nbpages.git
    - astrocut>=0.5
    - spectral-cube
    - astropy
    - aplpy
    - multiprocess
    - corner
    - emcee
    - ipyvuetify==1.4.1
    - ipyvue==1.3.4
    - git+https://github.com/mtakahiro/gsf@v1.2.3#egg=gsf
    - git+https://github.com/spacetelescope/jwst.git
    - git+https://github.com/glue-viz/glue.git
    - git+https://github.com/glue-viz/glue-jupyter.git
    - git+https://github.com/spacetelescope/jdaviz.git
