name: notebooks_env


channels:
  - astropy
  - http://ssb.stsci.edu/astroconda
  - defaults

dependencies:
  - pip
  - numpy
  - astropy
  - scipy
  - astroquery
  - matplotlib
  - jupyter
  - pandas
  - drizzlepac
  - crds
  - ccdproc
  - acstools
  - photutils>=0.6
  - regions
  - pyregion
  - webbpsf>=0.8
  - scikit-learn
  - lmfit>=0.9
  - specutils
  - dill
  - dust_extinction
  
  - pip:
    - k2flix
    - junit_xml
    - git+https://github.com/eteq/nbpages.git
    - astrocut>=0.5
    - git+https://github.com/spacetelescope/jdaviz

